spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:tutor_link}?useSSL=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10

  data:
    redis:
      password: ${REDIS_PASSWORD}

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

logging:
  level:
    com.tutorlink: INFO
