-- V1: 用户相关表
CREATE TABLE `user` (
    `id`              BIGINT       NOT NULL COMMENT 'Snowflake ID',
    `phone`           VARCHAR(20)  DEFAULT NULL COMMENT '加密手机号',
    `phone_hash`      VARCHAR(64)  DEFAULT NULL COMMENT 'SHA-256 hash for lookup',
    `password`        VARCHAR(128) DEFAULT NULL COMMENT 'BCrypt hash',
    `wx_openid`       VARCHAR(64)  DEFAULT NULL COMMENT 'WeChat OpenID',
    `wx_unionid`      VARCHAR(64)  DEFAULT NULL COMMENT 'WeChat UnionID',
    `nickname`        VARCHAR(50)  NOT NULL COMMENT 'Display name',
    `avatar_url`      VARCHAR(512) DEFAULT NULL COMMENT 'Avatar URL',
    `gender`          TINYINT      DEFAULT 0 COMMENT '0=unknown,1=male,2=female',
    `role`            TINYINT      NOT NULL COMMENT '1=parent,2=tutor,4=admin (bitmask)',
    `status`          TINYINT      NOT NULL DEFAULT 1 COMMENT '0=disabled,1=active,2=banned',
    `last_login_time` DATETIME     DEFAULT NULL,
    `last_login_ip`   VARCHAR(45)  DEFAULT NULL,
    `is_deleted`      TINYINT      NOT NULL DEFAULT 0,
    `create_time`     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time`     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_phone_hash` (`phone_hash`),
    UNIQUE KEY `uk_wx_openid` (`wx_openid`),
    KEY `idx_role` (`role`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户账号表';

CREATE TABLE `user_profile` (
    `id`              BIGINT       NOT NULL,
    `user_id`         BIGINT       NOT NULL COMMENT 'FK -> user.id',
    `real_name`       VARCHAR(50)  DEFAULT NULL COMMENT 'Real name (encrypted)',
    `contact_phone`   VARCHAR(20)  DEFAULT NULL COMMENT 'Contact phone (encrypted)',
    `province`        VARCHAR(30)  DEFAULT NULL,
    `city`            VARCHAR(30)  DEFAULT NULL,
    `district`        VARCHAR(30)  DEFAULT NULL,
    `address_detail`  VARCHAR(200) DEFAULT NULL,
    `longitude`       DECIMAL(10,7) DEFAULT NULL,
    `latitude`        DECIMAL(10,7) DEFAULT NULL,
    `is_deleted`      TINYINT      NOT NULL DEFAULT 0,
    `create_time`     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time`     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_user_id` (`user_id`),
    KEY `idx_location` (`longitude`, `latitude`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='家长档案表';

CREATE TABLE `tutor_profile` (
    `id`                  BIGINT        NOT NULL,
    `user_id`             BIGINT        NOT NULL COMMENT 'FK -> user.id',
    `real_name`           VARCHAR(50)   DEFAULT NULL COMMENT 'Real name (encrypted)',
    `university`          VARCHAR(100)  DEFAULT NULL,
    `major`               VARCHAR(100)  DEFAULT NULL,
    `enrollment_year`     INT           DEFAULT NULL,
    `education_level`     TINYINT       DEFAULT NULL COMMENT '1=undergraduate,2=master,3=phd',
    `certification_status` TINYINT      NOT NULL DEFAULT 0 COMMENT '0=none,1=pending,2=approved,3=rejected',
    `certification_time`  DATETIME      DEFAULT NULL,
    `intro`               VARCHAR(500)  DEFAULT NULL,
    `teaching_style`      VARCHAR(300)  DEFAULT NULL,
    `hourly_rate_min`     INT           DEFAULT NULL COMMENT 'Min hourly rate in cents',
    `hourly_rate_max`     INT           DEFAULT NULL COMMENT 'Max hourly rate in cents',
    `avg_rating`          DECIMAL(2,1)  NOT NULL DEFAULT 0.0,
    `rating_count`        INT           NOT NULL DEFAULT 0,
    `order_count`         INT           NOT NULL DEFAULT 0,
    `province`            VARCHAR(30)   DEFAULT NULL,
    `city`                VARCHAR(30)   DEFAULT NULL,
    `district`            VARCHAR(30)   DEFAULT NULL,
    `longitude`           DECIMAL(10,7) DEFAULT NULL,
    `latitude`            DECIMAL(10,7) DEFAULT NULL,
    `is_online`           TINYINT       NOT NULL DEFAULT 0,
    `is_deleted`          TINYINT       NOT NULL DEFAULT 0,
    `create_time`         DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time`         DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_user_id` (`user_id`),
    KEY `idx_certification` (`certification_status`),
    KEY `idx_rating` (`avg_rating` DESC),
    KEY `idx_location` (`longitude`, `latitude`),
    KEY `idx_hourly_rate` (`hourly_rate_min`, `hourly_rate_max`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='家教档案表';
